### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by NinjaNymo** [ntnu-itk/labreport#1]
When importing the whole project into ShareLatex I get the following compile error. Any ideas?

Emergency stop.

```
<*> preamble.tex
                
*** (job aborted, no legal \end found)

 
Here is how much of TeX's memory you used:
 25114 strings out of 493013
 457219 string characters out of 6133329
 741698 words of memory out of 5000000
 28292 multiletter control sequences out of 15000+600000
 4709 words of font info for 16 fonts, out of 8000000 for 9000
 1141 hyphenation exceptions out of 8191
 62i,0n,72p,899b,219s stack positions out of 5000i,500n,10000p,200000b,80000s
!  ==> Fatal error occurred, no output PDF file produced!
```

**Comment by krisgry** [comment]
Thanks for filing this report! Apparently, sharelatex does not support having the "documentclass" definition in a separate file, so [this commit](https://github.com/ntnu-itk/labreport/commit/4877cd30ad545045eccb86b8389eb7b7d38ea93) fixes things.

@anlif we could consider changing preamble.tex to a package, making it more robust against errors caused by (accidental) multiple imports ( according to [sharelatex](https://no.sharelatex.com/learn/Management_in_a_large_project#/Preamble_in_a_separate_file) )

**Comment by anlif** [comment]
Aha. Looks like making the preamble into a package is a reasonable thing to do. @krisgry fix?

**Comment by krisgry** [comment]
Changed preamble.tex into kyblab.sty
